---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - config.yml

  tasks:
  - name: Create SSH public key file
    command: "php {{ playbook_dir }}/merge-public-keys.php staff /home/{{ ssh_user }}/.ansible/tmp/staff-public-keys.conf"
    register: php_output
    changed_when: php_output.stdout != 'SKIPPING'

  - name: Set correct permissions on .ssh folder
    file: path=/home/{{ ssh_user }}/.ssh state=directory owner={{ ssh_user }} group=studio24 mode=0700

  - name: Update SSH public keys in authorized_keys file
    template: src=/home/{{ ssh_user }}/.ansible/tmp/staff-public-keys.conf dest=/home/{{ ssh_user }}/.ssh/authorized_keys owner={{ ssh_user }} group={{ ssh_user }} mode=0600
